version: '3'

services:
  web:
    build: .
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "81:81"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - web
